### ISSUE TITLE
You must supply a layout_width attribute

### ISSUE THREAD

**Issue by Duna** [MrEngineer13/SnackBar#92]
Caused by: java.lang.UnsupportedOperationException: Binary XML file line #7: You must supply a layout_width attribute.
        at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:779)
        at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:8147)
        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:8339)
        at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:439)
        at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:370)
        at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:56)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.github.mrengineer13.snackbar.SnackBar.<init>(SnackBar.java:77)
        at com.github.mrengineer13.snackbar.SnackBar$Builder.<init>(SnackBar.java:128)
        at com.million.duna.basefragments.FragmentGame$MyEventBus$3.run(FragmentGame.java:235)

**Comment by MrDick-11** [comment]
got the same error. Any solution?

**Comment by feihong247** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by MrDick-11** [comment]
solved by copying sb_snack.xml to layouts and adding
android:layout_width="match_parent"
android:layout_height="match_parent"
